// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A3bh6ucarqa-9wEDstndUhRfKTEtf4c',
    appId: '1:1080418148651:web:a55801eb6617ff9a1b656e',
    messagingSenderId: '1080418148651',
    projectId: 'moodify-5301b',
    authDomain: 'moodify-5301b.firebaseapp.com',
    storageBucket: 'moodify-5301b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzOORadqGx2pZY15h4gvU7SDsm-3I-d5c',
    appId: '1:1080418148651:android:70b22f4493532ad11b656e',
    messagingSenderId: '1080418148651',
    projectId: 'moodify-5301b',
    storageBucket: 'moodify-5301b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOdBFjxlEcWtVNjCVgv-fEvBHqs3m82jo',
    appId: '1:1080418148651:ios:d84eb9adbaecf19f1b656e',
    messagingSenderId: '1080418148651',
    projectId: 'moodify-5301b',
    storageBucket: 'moodify-5301b.firebasestorage.app',
    iosBundleId: 'com.example.moodify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOdBFjxlEcWtVNjCVgv-fEvBHqs3m82jo',
    appId: '1:1080418148651:ios:d84eb9adbaecf19f1b656e',
    messagingSenderId: '1080418148651',
    projectId: 'moodify-5301b',
    storageBucket: 'moodify-5301b.firebasestorage.app',
    iosBundleId: 'com.example.moodify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_A3bh6ucarqa-9wEDstndUhRfKTEtf4c',
    appId: '1:1080418148651:web:533a2927afbddb441b656e',
    messagingSenderId: '1080418148651',
    projectId: 'moodify-5301b',
    authDomain: 'moodify-5301b.firebaseapp.com',
    storageBucket: 'moodify-5301b.firebasestorage.app',
  );
}
